### ISSUE TITLE
Chart index looks outdated - envoy 0.0.11 and 0.0.12 missing

### ISSUE THREAD

**Issue by n0v1** [slamdev/helm-charts#17]
Hi @slamdev,

today I tried upgrading to the latest version of your Envoy chart (0.0.12) but helm complained that it can't find it when executing `helm dependency update`:

> Error: can't get a valid version for repositories envoy. Try changing the version constraint in Chart.yaml

When looking at https://slamdev.github.io/helm-charts/index.yaml I only see versions `0.0.1` to `0.0.10`. `0.0.11` and `0.0.12` seem to be missing. At least `0.0.11` was there some days ago. Can you please check?

My `Chart.yaml` looks like this:
```yaml
apiVersion: v2
name: my-gateway
type: application
version: 1.0.0
appVersion: v1.19.0

dependencies:
  - name: envoy
    version: 0.0.11
    repository: "https://slamdev.github.io/helm-charts/"
```
