### ISSUE TITLE
support pvc?

### ISSUE THREAD

**Issue by davidkarlsen** [slamdev/helm-charts#2]
do you think it would maybe be useful to support a pvc via storageclass?

**Comment by slamdev** [comment]
@davidkarlsen what chart are you referring to?

**Comment by cdmaslo** [comment]
I am not sure about @davidkarlsen, but for me I would like to see support in archiva. Thanks a lot.

**Comment by davidkarlsen** [comment]
> @davidkarlsen what chart are you referring to?

Ah - sorry - forgot to mention that and lost track of the issue. I was thinking of the gradle-cache one.

**Comment by slamdev** [comment]
@cdmaslo @davidkarlsen volumes list is fully customizable, you can refer to an existing **PersistentVolumeClaim** in values.yaml like this:
```yaml
# volumes -- volumes
volumes:
  - name: data
    persistentVolumeClaim:
      claimName: the-claim-you-created
```
