### ISSUE TITLE
gradle-cache crashloopback

### ISSUE THREAD

**Issue by patsevanton** [slamdev/helm-charts#49]
```
Warning  BackOff    9m27s (x497 over 131m)  kubelet  Back-off restarting failed container gradle-cache in pod gradle-cache-7b48c8648d-hhznk_gradle-cache (4b6172c7-9c12-4f6e-8ed2-90e5658ae2a9)                                                                                                                     
Warning  Unhealthy  4m31s (x290 over 134m)  kubelet  Readiness probe failed: Get "http://10.240.21.216:5071/": dial tcp 10.240.21.216:5071: connect: connection refused 
```

values.yaml
```
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer
      hosts:
        - host: gradle-cache.my.corp
          paths:
            - /
      tls:
        - secretName: gradle-cache-tls
          hosts:
            - gradle-cache.my.corp
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    affinity: {}
    volumes:
      - name: cache
        emptyDir: {}
```
